// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7SCH2MTd9WI_4gEzLR_U0ph1aXoZjK3o',
    appId: '1:870219019758:web:ebcbbb7d9a5db268ae0aff',
    messagingSenderId: '870219019758',
    projectId: 'instapay-flutter',
    authDomain: 'instapay-flutter.firebaseapp.com',
    storageBucket: 'instapay-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7175_PfXrZ-GnO89oP-vbFjR3YwhetzA',
    appId: '1:870219019758:android:01a3f04bcc81b61eae0aff',
    messagingSenderId: '870219019758',
    projectId: 'instapay-flutter',
    storageBucket: 'instapay-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO7HBfGX90aOKFOc8QZKRUUVrc60Okz4k',
    appId: '1:870219019758:ios:3bf435c10815ce6aae0aff',
    messagingSenderId: '870219019758',
    projectId: 'instapay-flutter',
    storageBucket: 'instapay-flutter.appspot.com',
    iosClientId: '870219019758-302ke0lban224neb8nls1ejr2gqg151e.apps.googleusercontent.com',
    iosBundleId: 'com.instapay.njw9108.instapayClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO7HBfGX90aOKFOc8QZKRUUVrc60Okz4k',
    appId: '1:870219019758:ios:3bf435c10815ce6aae0aff',
    messagingSenderId: '870219019758',
    projectId: 'instapay-flutter',
    storageBucket: 'instapay-flutter.appspot.com',
    iosClientId: '870219019758-302ke0lban224neb8nls1ejr2gqg151e.apps.googleusercontent.com',
    iosBundleId: 'com.instapay.njw9108.instapayClone',
  );
}
